config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts, path: '/'
  resources :tags, only: %i[show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_rich_text :content

  belongs_to :author, class_name: 'User', optional: true
  has_many :taggables, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggables

  ##
  # Method for defining meta-tag related data
  # @see https://github.com/kpumuk/meta-tags#using-metatags-in-view
  #
  def to_meta_tags
    {
      title: title,
      description: content.to_plain_text.truncate(300),
    }
  end

  ##
  # Helper method for displaying the author either with name or email
  #
  def display_author
    return 'Anonymous' if author.blank?

    author.name || author.email
  end
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_many :users, through: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :taggables, dependent: :destroy

  validates :name, uniqueness: { case_sensitive: false }

  before_validation :clean_name

  ##
  # Method for defining meta-tag related data
  # @see https://github.com/kpumuk/meta-tags#using-metatags-in-view
  #
  def to_meta_tags
    {
      title: name
    }
  end

  private

  def clean_name
    name.strip!
  end
end

app/models/taggable.rb
# frozen_string_literal: true

class Taggable < ApplicationRecord
  belongs_to :tag
  belongs_to :taggable, polymorphic: true

  # Delegate method calls to taggable
  delegate :title, :display_author, :tags, :content, to: :taggable
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :nullify, inverse_of: :author

  def admin?
    has_role?(:admin)
  end

  def author?
    has_role?(:author)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  layout :layout_by_resource

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  ##
  # Prefer the application.html.erb layout unless it is a Devise
  # controller
  #
  def layout_by_resource
    if devise_controller?
      'devise'
    else
      'application'
    end
  end

  ##
  # Handle a Pundit authorization failure gracefully
  #
  def user_not_authorized
    flash[:error] = 'You are not authorized to perform this action.'
    redirect_to(request.referer || root_path)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_post, only: %i[show edit update]
  before_action :authorize_post, only: %i[show edit update]

  def index
    @posts = Post.all.order(created_at: :desc)
    if params[:tag]
      @posts = @posts.joins(:tags).where(tags: { name: params[:tag] })
      set_meta_tags title: params[:tag],
                    keywords: params[:tag]
    end
    @posts = @posts.page(params[:page])
    authorize @posts
  end

  def new
    @post = Post.new
    authorize @post
    set_meta_tags title: 'New Post'
  end

  def create
    # Use strong params and merge current user as the author
    clean_params = post_params
    clean_params.merge!(author: current_user)

    @post = Post.new(clean_params)
    authorize @post

    if @post.save
      handle_tags
      flash[:success] = 'Created the post successfully!'
      redirect_to post_path(@post)
    else
      flash[:error] = @post.errors.full_messages.to_sentence
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @post.update(post_params)
      handle_tags
      flash[:success] = 'Updated the post successfully!'
      redirect_to post_path(@post)
    else
      flash[:error] = @post.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @post = Post.find_by(slug: params[:id])
    authorize @post

    @post&.destroy
    if @post.nil? || @post.destroyed?
      flash[:success] = 'Deleted the post successfully!'
      redirect_to root_path
    else
      flash[:error] = @post.errors.full_messages.to_sentence
      redirect_to edit_post_path(@post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  ##
  # Return the join param for Tags only
  #
  def tags_param
    params.require(:post).permit(:tags).dig(:tags)
  end

  ##
  # Sets the @post variables based on the :id param
  #
  def set_post
    @post = Post.friendly.find(params[:id])
    set_meta_tags @post
  end

  ##
  # Authorizes via Pundit the post
  #
  def authorize_post
    authorize @post
  end

  ##
  # Makes sure post has all required tags based on
  # submitted params
  #
  def handle_tags
    return if tags_param.blank?

    tag_names = tags_param.split(',')
    tags = tag_names.map do |name|
      Tag.find_or_create_by(name: name)
    end
    @post.tags = tags
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  before_action :set_tag, only: %i[show]

  def show
    @posts = @tag.taggables.order(created_at: :desc).page(params[:page])
    authorize @posts
  end

  private

  ##
  # Sets the @tag variables based on the :id param
  #
  def set_tag
    @tag = Tag.find_by!(name: CGI.unescape(params[:id]))
    set_meta_tags @tag
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  ##
  # Translates a flash message key into a Bulma-friendly
  # is-class variable
  #
  # @see https://bulma.io/documentation/elements/notification/
  #
  def bulma_flash_class(key)
    key = key.to_sym # Ensure we are working with a symbol

    case key
    when :error
      :danger
    when :notice
      :success
    when :alert
      :warning
    else
      key
    end
  end

  ##
  # Returns a list of valid tags listed alphabetically
  #
  def tags
    Tag.order(:name)
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags site: 'Eric Saupe', reverse: true %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <%= render partial: 'shared/flash' %>

    <section class="section">
      <%= yield %>
    </section>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags site: 'Eric Saupe', reverse: true %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <%= render partial: 'shared/flash' %>

    <section class="section">
      <div class="columns">
        <div class="column is-half is-offset-one-quarter">
          <%= yield %>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <div class="field">
    <%= form.label :title, class: 'label' %>
    <div class="control">
      <%= form.text_field :title, class: 'input', required: true %>
    </div>
  </div>

  <div class="field">
    <%= form.label :tags, class: 'label' %>
    <div class="control">
      <%= form.text_field :tags, type: 'tags', value: post.tags&.pluck(:name)&.join(','), data: { controller: 'tag' } %>
    </div>
  </div>
  
  <div class="field">
    <%= form.label :content, class: 'label' %>
    <div class="control">
      <%= form.rich_text_area :content, required: true %>
    </div>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= form.submit 'Submit', class: 'button is-link' %>
    </div>
    <% if post.persisted? %>
      <div class="control">
        <%= link_to 'Delete', 
          post_path(post), 
          method: :delete, 
          class: 'button is-danger', 
          data: {
            confirm: 'Are you sure you want to delete this?'
          } 
        %>
      </div>
    <% end %>
    <div class="control">
      <%= form.button 'Cancel', class: 'button is-text' %>
    </div>
  </div>
<% end %>

app/views/posts/_tags.html.erb
<div class="row">
  <div class="tags">
    <% post.tags.each do |tag| %>
      <%= link_to tag.name, posts_path(tag: tag.name), class: 'tag is-link' %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1 class="title">Edit Post</h1>
<h2 class="subtitle"><%= @post.title %></h2>
<%= render partial: 'form', locals: { post: @post } %>

app/views/posts/index.html.erb
<% if @tag %>
  <h1 class="title"><%= @tag.name %></h1>
<% end %>

<% @posts.each do |post| %>
  <article id="post-<%= post.id %>" class="message">
    <div class="message-header">
      <p>
        <%= link_to post.title, post_path(post) %>
        by <%= post.display_author %>
        on <%= post.created_at.strftime('%B %e, %Y') %>
      </p>
      <%= link_to('Edit', edit_post_path(post), class: 'button is-link') if policy(post).edit? %>
    </div>
    <div class="message-body">
      <%= render partial: 'shared/tags', locals: { post: post } %>
      <p class="content">
        <%= truncate(post.content.to_plain_text, length: 1000, omission: '...') %>
      </p>
      <%= render partial: 'shared/actions', locals: { post: post } %>
    </div>
  </article>
<% end%>

<%= paginate @posts %>

app/views/posts/new.html.erb
<h1 class="title">New Post</h1>
<%= render partial: 'form', locals: { post: @post } %>

app/views/posts/show.html.erb
<h1 class="title"><%= @post.title %></h1>
<h2 class="subtitle">
  By <%= @post.display_author %>
  on <%= @post.created_at.strftime('%B %e, %Y') %>
</h2>
<%= render partial: 'shared/tags', locals: { post: @post } %>
<%= @post.content %>

app/views/shared/_actions.html.erb
<div class="row">
  <%= link_to 'Keep Reading →', post_path(post), class: 'button is-primary' %>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div 
    class="notification is-<%= bulma_flash_class(key) %>" 
    data-controller="flash"
    data-target="flash.notification"
  >
    <button 
      class="delete"
      data-action="click->flash#close"
    ></button>
    <%= value %>
  </div>
<% end %>

app/views/shared/_mobile_menu.html.erb
<div class="mobile-menu sidebar is-hidden-desktop" data-target="sidebar.container">
  <div class="sidebar-overlay" data-action="click->sidebar#close"></div>
  <div class="sidebar-content is-right">
    <header class="mobile-menu-header">
      <%= render partial: 'shared/mobile_menu/header' %>
    </header>
    <div class="mobile-menu-content">
      <%= render partial: 'shared/mobile_menu/content' %>
    </div>
    <footer class="mobile-menu-footer">
      <%= render partial: 'shared/mobile_menu/footer' %>
    </footer>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand" data-controller="sidebar">
    <%= link_to root_path, class: 'navbar-item' do %>
      <%= image_tag 'logo.svg', width: '150px' %>
    <% end %>

    <div
        class="navbar-burger burger"
        data-action="click->sidebar#open"
        data-target="sidebar.trigger" >
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </div>
    <%= render partial: 'shared/mobile_menu' %>
  </div>

  <div class="navbar-menu">
    <div class="navbar-start">
      <%= link_to 'Home', root_path, class: 'navbar-item' %>

      <% if tags.present? %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Tags
          </a>

          <div class="navbar-dropdown">
            <% tags.each do |tag| %>
              <%= link_to tag.name, tag_path(id: CGI.escape(tag.name)), class: 'navbar-item' %>
            <% end %>
          </div>
        </div>
      <% end %>

      <%= link_to('New Post', new_post_path, class: 'navbar-item') if policy(Post).new? %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'button is-light' %>
          <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'button is-primary'%>
            <%= link_to 'Log in', new_user_session_path, class: 'button is-light'%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_tags.html.erb
<div class="row">
  <div class="tags">
    <% post.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(id: CGI.escape(tag.name)), class: 'tag is-link' %>
    <% end %>
  </div>
</div>

app/views/shared/mobile_menu/_content.html.erb
<div class="menu"></div>

app/views/shared/mobile_menu/_footer.html.erb
<div class="menu">
  <ul class="menu-list has-text-centered is-size-4">
    <% if user_signed_in? %>
      <li>
        <%= link_to('Log out', destroy_user_session_path, method: :delete, class: 'button is-light') %>
      </li>
    <% else %>
      <li>
        <%= link_to('Log in', new_user_session_path, class: 'button is-light') %>
        <%= link_to('Sign up', new_user_registration_path, class: 'button is-primary') %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/mobile_menu/_header.html.erb
<div class="hero is-primary">
  <div class="hero-body">
    <% if user_signed_in? %>
      <div class="media">
        <div class="media-left"></div>
        <div class="media-content">
          <p class="title is-4">
            <%= current_user.email %>
          </p>
        </div>
      </div>
    <% else %>
      <div class="not-logged-in has-text-centered">
        <p class="title is-6 is-uppercase is-marginless">
          Welcome to
        </p>
        <figure class="image logo is-centered is-128x128 is-vcentered">
          <%= image_tag 'logo.svg' %>
        </figure>
      </div>
    <% end %>
  </div>
</div>

app/views/tags/show.html.erb
<%= render template: 'posts/index' %>